language: node_js
node_js:
  - 14.18.1 
services:
  - postgresql
before_script:
  - psql -c 'create database acme_db;' -U postgres
env:
  - JWT=f00B@rBazz
  - JWT_SECRET=mfefkuhio3k2rjkofn2mbikbkwjhnkj
  - clientURL=localhost://3000
